spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/securityService
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: HS9ffEi_MQWPEq5MWvmL # 숨겨야함
            client-secret: K2PfTErz4W # 숨겨야함
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - nickname
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

app:
  auth:
    token-expiration-msec: 864000000
    token-secret: F6bxqUhrYpOLvjgiATOi3S3YYZQyC2uHYrsiXqOikD+L6mbaBNWFIGProM1gbVSFw5/28BKHYkzyVUyc7o8HDUyBiBKDAMIftw1bf1bFVnuOgGEs80iabjfVcKgoUa+PnF1SdMsas3oR4Dgf0C80HsceUwWZipNg0m4vwjJuC1VZw3OMwY
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect