spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/securityService
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: HS9ffEi_MQWPEq5MWvmL # 숨겨야함
            client-secret: K2PfTErz4W # 숨겨야함
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver" # "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email, gender, age, birthday, birthyear, mobile
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 인증 창으로 이동 -> 사용자 동의 -> 돟의 정보를 포함한 채로 Callback Url에 전송
            token_uri: https://nid.naver.com/oauth2.0/token # Callback으로 전달받은 정보를 이용해 Access Token 발급. Access Token : 사용자가 인증을 완료했음을 뜻함 -> 프로필 API를 호출하거나 open API호출 가능
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 조회하는 프로필 api 호출
            user_name_attribute: response # 프로필 API 호출 후 출력 결과가 response : { ... } 로 나오기 때문. response는 결국 key값

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

app:
  oauth2:
    authorizedRedirectUris:
      - redirectUrl